apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: myq-components
  description: A collection of myq components
spec:
  targets:
    - ./components/community-events-writer.yaml
    - ./components/devices-api.yaml
